# Results-PR-Build: https://dev.azure.com/neesh90900932/PythonWorks/_build?definitionId=2&_a=summary
name: Results Microservice - Build and Push to ACR

#Adding path based trigger as this pipeline only should trigger if changes made in results microservices.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  - group: voting-platform-secrets
  - name: dockerRegistryServiceConnection
    value: $(ACRRegistryServiceConnection)
  - name: imageRepository
    value: 'votingappmicrovotingplatformappimage'
  - name: containerRegistry
    value: $(ContainerRegistry)
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/result/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: Push
  displayName: Push to Azure Container Registry
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: PushJob
    displayName: Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Push image to ACR
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)
