# Results-PR-Build: https://dev.azure.com/neesh90900932/PythonWorks/_build?definitionId=2&_a=summary
name: Results Microservice - Build and Push to ACR

#Adding path based trigger as this pipeline only should trigger if changes made in results microservices.
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
- group: voting-platform-secrets
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'da1b292c-c2ea-40db-b712-54ab3ea1bba1'
  imageRepository: 'votingappmicrovotingplatformappimage'
  containerRegistry: $(ContainerRegistry)
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
